### PR TITLE
#63 - pmp_pushed date and button color

### PR DESCRIPTION
**Pull request by johnsonpaul1014**
I added some code to add a meta field for "pmp_pushed" with the date the push happened.  We are also going to use this to determine if feeds should be syndicated if they have gone to the PMP.  We weren't sure about the button styling.  All that really matters is that it looks a bit different.

### CODE REVIEW

**Comment by cavis** [comment]
/me paraphrasing a question from @rnagle ...

> Could we avoid adding another meta field here?  Couldn't this information be inferred from the `pmp_guid` and `pmp_owner` custom fields`?

Meaning... if the Post is in the PMP (has a guid) and you own it (the `pmp_owner` guid is you), can't we assume that you pushed it?

**Comment by cavis** [comment]
My thoughts... there are some edge cases where that wouldn't be true:

* You (your PMP user) pushed the Post from somewhere else (a different Wordpress install or something) and pulled it down to this Wordpress site.
* Someone else pushes content "on your behalf", setting `links.owner` to be you.

And sorry to "overthink" this - just want to make absolutely sure we need another custom field.  And that this is the correct custom field for these purposes.

**Comment by cavis** [comment]
Also @johnsonpaul1014 - I just pushed some updates to master to help run unit tests locally.  Just run `make install` and `make test` on some sort of osx/nix system.  (Hopefully it'll just work - I've only tested it locally on my mac).

**Comment by johnsonpaul1014** [comment]
I looked at the current post meta being stored, and I didn't see one that was the time of the push, unless I missed something.  I would rather have that than just the fact that it was pushed, although I realize this does entail the use of an additional field and perhaps it isn't worth it.  I just thought this would be nice information for the user to have.  I'll take a look at the testing stuff now.

**Comment by cavis** [comment]
Okay, so for my own sanity, the current relevant pieces of data here are:

1. The fact that the Post exists in the PMP (the `pmp_guid`)
2. When the Post/Story was published (the `pmp_published` timestamp - which is not the same as last modified)
3. When the Post/Story was modified (the `pmp_modified` timestamp - which is updated EVERY time anyone touches the doc in the PMP)
4. Your ability to write to the PMP-Story (inferred from the `owner_guid` right now ... BUT this just means your PMP-user owns it, not that your Wordpress site pushed it)

I think (3) will get you half of what you want.  For (4) ... that *would* work, if you didn't care whether or not the PMP-Story originated from your specific Wordpress site.

So... for your use case, do you care if the PMP-story originated from the specific site?  Or just that you own it, and it was modified (from somewhere) on X date?

**Comment by johnsonpaul1014** [comment]
I changed the code to use the `pmp_modified` variable, as that is really fine for our purposes.  I also added a filter before save, because the actions that were there weren't enough as I needed to modify the PMP document before sending it to the PMP to tweak it based on extra information we are storing for the post.

Also, I was able to run the tests, but I kept getting errors about `contentencoded` being undefined, and I don't see how my code would have affected this logic.  Any thoughts?

**Comment by cavis** [comment]
Not rightly sure on the `contentencoded` bit.  Is the test perhaps trying to pull a piece of PMP content that your user doesn't have access to?  (Are there actual PMP guids hardcoded in the tests?)

I may still need to do some work on my "test setup" Makefile.  It doesn't seem to be working for me, when I do a fresh checkout of the repo.

Your travis-ci build failures seem to be caused by a lack of ENV variables.  I guess that travis [won't set "secure" environment variables](http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests) when building PR's.  So that's a bummer.  I'm digging around a bit for alternatives.  Maybe this is an argument for recording all http transactions as fixtures in the tests.

**Comment by rnagle** [comment]
This looks good to me. The only change I think we should make is related to the call to [`apply_filters`](https://github.com/publicmediaplatform/pmp-wordpress/pull/64/files#diff-7fe6e55397c77ab9a0f5d57bc4cbe5b9R278).

I think we should change the block of code to look like this:

    $doc = apply_filters('pmp_before_push', $doc, $post->ID);
    $doc->save();
    do_action('pmp_after_push', $doc, $post->ID);

Using `apply_filters` makes more sense than `do_action` before calling the `save` method.

Note: the call to `do_action` includes the variable `$doc` with this change.

Also note: I suggest we use the filter name `pmp_before_push` instead of `pmp_doc` since it is a bit more verbose/descriptive.

@johnsonpaul1014 Making this change would mean you'd have to update whatever code using the `pmp_doc` filter to use `pmp_before_push` instead.

Thanks for the pull request! ^_^

**Comment by rnagle** [comment]
Looks good to me!

**Comment by cavis** [comment]
Fixes #67.  Opened #70 for myself - to get builds working on these PR's at some point.

:shipit:!

**Pull request merged**
